env: toygame

env_args:
  n_agents: 2
  n_actions: 2
  episode_limit: 2
  seed: None

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 55000
test_interval: 10000
test_nepisode: 300
test_greedy: True